<a href="https://colab.research.google.com/github/albertorm/MTA_request/blob/master/Washoe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
# Load data to dataframes
df_stops = pd.read_csv('stops.txt')
df_trips = pd.read_csv('trips.txt')
df_stoptimes = pd.read_csv('stop_times.txt')
df_routes = pd.read_csv('routes.txt')

In [0]:
# Join stoptimes to trips to get route id
df_trip_stops =  df_stoptimes.join(df_trips.set_index('trip_id'), 
                                   on = 'trip_id', 
                                   how = 'left')[['trip_id','arrival_time','departure_time','stop_id','stop_sequence','route_id']]

In [0]:
# Join df to routes to obtain route short name
df_trip_stops = df_trip_stops.merge(df_routes, 
                                    on = 'route_id', 
                                    how = 'left')[['trip_id','arrival_time','departure_time','stop_id','stop_sequence','route_id','route_short_name']]

In [0]:
# Create a dummy value with next stop sequence id
df_trip_stops['next_stop_seq'] = df_trip_stops['stop_sequence']+1

In [0]:
# Join again to stoptimes to get the next stop id
df_trip_stops['next_stop_id'] = df_trip_stops.merge(df_stoptimes, 
                         left_on  = ['trip_id','next_stop_seq'], 
                         right_on = ['trip_id','stop_sequence'], 
                         how = 'left')[['stop_id_y']]

In [0]:
# present only relevant columns 
df_format = df_trip_stops[['trip_id','route_id','route_short_name','stop_id','next_stop_id','departure_time','arrival_time']]

In [0]:
# print output
df_format

,trip_id,route_id,route_short_name,stop_id,next_stop_id,departure_time,arrival_time
0,432701-1801-1801-Weekday-01,26-63,26,1921,1899.0,06:05:00,06:05:00
1,432701-1801-1801-Weekday-01,26-63,26,1899,1900.0,06:06:00,06:06:00
2,432701-1801-1801-Weekday-01,26-63,26,1900,574.0,06:07:00,06:07:00
3,432701-1801-1801-Weekday-01,26-63,26,574,575.0,06:08:00,06:08:00
4,432701-1801-1801-Weekday-01,26-63,26,575,1413.0,06:08:00,06:08:00
5,432701-1801-1801-Weekday-01,26-63,26,1413,576.0,06:09:00,06:09:00
6,432701-1801-1801-Weekday-01,26-63,26,576,577.0,06:09:00,06:09:00
7,432701-1801-1801-Weekday-01,26-63,26,577,539.0,06:10:00,06:10:00
8,432701-1801-1801-Weekday-01,26-63,26,539,559.0,06:11:00,06:11:00
9,432701-1801-1801-Weekday-01,26-63,26,559,281.0,06:11:00,06:11:00
10,432701-1801-1801-Weekday-01,26-63,26,281,579.0,06:12:00,06:12:00
11,432701-1801-1801-Weekday-01,26-63,26,579,580.0,06:12:00,06:12:00
12,432701-1801-1801-Weekday-01,26-63,26,580,1201.0,06:13:00,06:13:00
13,432701-1801-1801-Weekday-01,26-63,26,1201,1202.0,06:14:00,06:14:00
14,432701-1801-1801-Weekday-01,26-63,26,1202,1414.0,06:16:00,06:16:00
15,432701-1801-1801-Weekday-01,26-63,26,1414,1159.0,06:17:00,06:17:00
16,432701-1801-1801-Weekday-01,26-63,26,1159,1295.0,06:18:00,06:18:00
17,432701-1801-1801-Weekday-01,26-63,26,1295,588.0,06:20:00,06:20:00
18,432701-1801-1801-Weekday-01,26-63,26,588,NaN,06:20:00,06:20:00
19,432702-1801-1801-Weekday-01,26-63,26,1921,1899.0,09:05:00,09:05:00
20,432702-1801-1801-Weekday-01,26-63,26,1899,1900.0,09:06:00,09:06:00
21,432702-1801-1801-Weekday-01,26-63,26,1900,574.0,09:07:00,09:07:00
22,432702-1801-1801-Weekday-01,26-63,26,574,575.0,09:08:00,09:08:00
23,432702-1801-1801-Weekday-01,26-63,26,575,1413.0,09:08:00,09:08:00
24,432702-1801-1801-Weekday-01,26-63,26,1413,576.0,09:09:00,09:09:00
25,432702-1801-1801-Weekday-01,26-63,26,576,577.0,09:09:00,09:09:00
26,432702-1801-1801-Weekday-01,26-63,26,577,539.0,09:10:00,09:10:00
27,432702-1801-1801-Weekday-01,26-63,26,539,559.0,09:11:00,09:11:00
28,432702-1801-1801-Weekday-01,26-63,26,559,281.0,09:11:00,09:11:00
29,432702-1801-1801-Weekday-01,26-63,26,281,579.0,09:12:00,09:12:00
...,...,...,...,...,...,...,...
78940,436431-1801-1801-Sunday-01,16-63,16,1293,1961.0,16:38:00,16:38:00
78941,436431-1801-1801-Sunday-01,16-63,16,1961,NaN,16:40:00,16:40:00
78942,436432-1801-1801-Sunday-01,16-63,16,1504,1505.0,17:24:00,17:24:00
78943,436432-1801-1801-Sunday-01,16-63,16,1505,721.0,17:25:00,17:25:00
78944,436432-1801-1801-Sunday-01,16-63,16,721,722.0,17:26:00,17:26:00
78945,436432-1801-1801-Sunday-01,16-63,16,722,723.0,17:27:00,17:27:00
78946,436432-1801-1801-Sunday-01,16-63,16,723,724.0,17:27:00,17:27:00
78947,436432-1801-1801-Sunday-01,16-63,16,724,725.0,17:28:00,17:28:00
78948,436432-1801-1801-Sunday-01,16-63,16,725,726.0,17:29:00,17:29:00
78949,436432-1801-1801-Sunday-01,16-63,16,726,727.0,17:30:00,17:30:00
78950,436432-1801-1801-Sunday-01,16-63,16,727,729.0,17:34:00,17:34:00
78951,436432-1801-1801-Sunday-01,16-63,16,729,730.0,17:35:00,17:35:00
78952,436432-1801-1801-Sunday-01,16-63,16,730,1680.0,17:36:00,17:36:00
78953,436432-1801-1801-Sunday-01,16-63,16,1680,1293.0,17:37:00,17:37:00
78954,436432-1801-1801-Sunday-01,16-63,16,1293,1961.0,17:38:00,17:38:00
78955,436432-1801-1801-Sunday-01,16-63,16,1961,NaN,17:40:00,17:40:00
78956,436433-1801-1801-Sunday-01,16-63,16,1504,1505.0,18:24:00,18:24:00
78957,436433-1801-1801-Sunday-01,16-63,16,1505,721.0,18:25:00,18:25:00
78958,436433-1801-1801-Sunday-01,16-63,16,721,722.0,18:26:00,18:26:00
78959,436433-1801-1801-Sunday-01,16-63,16,722,723.0,18:27:00,18:27:00
78960,436433-1801-1801-Sunday-01,16-63,16,723,724.0,18:27:00,18:27:00
78961,436433-1801-1801-Sunday-01,16-63,16,724,725.0,18:28:00,18:28:00
78962,436433-1801-1801-Sunday-01,16-63,16,725,726.0,18:29:00,18:29:00
78963,436433-1801-1801-Sunday-01,16-63,16,726,727.0,18:30:00,18:30:00
78964,436433-1801-1801-Sunday-01,16-63,16,727,729.0,18:34:00,18:34:00
78965,436433-1801-1801-Sunday-01,16-63,16,729,730.0,18:35:00,18:35:00
78966,436433-1801-1801-Sunday-01,16-63,16,730,1680.0,18:36:00,18:36:00
78967,436433-1801-1801-Sunday-01,16-63,16,1680,1293.0,18:37:00,18:37:00
78968,436433-1801-1801-Sunday-01,16-63,16,1293,1961.0,18:38:00,18:38:00
78969,436433-1801-1801-Sunday-01,16-63,16,1961,NaN,18:40:00,18:40:00